### ISSUE TITLE
You could use `unliftio-core` instead of `unliftio`

### ISSUE THREAD

**Issue by evanrelf** [bellroy/unliftio-servant-server#1]
I noticed this package depends on the full fat `unliftio` package, and not the slim `unliftio-core` package that just provides the `MonadUnliftIO` type class.

It appears you're only importing `MonadUnliftIO` [here](https://github.com/bellroy/unliftio-servant-server/blob/c91cd898561c142fa382ccf2e045552d0dd27173/src/UnliftIO/Servant/Server.hs#L71), so you could get away with only using `unliftio-core`!

Not a big deal - anyone using `servant-server` is gonna have most if not all of the `unliftio` dependencies, so it probably doesn't matter - but I figured I'd mention it.

**Comment by JackKelly-Bellroy** [comment]
Good catch, thank you.
